import * as admin from "firebase-admin";
import { Logger } from "../shared/logger/logger";

export interface NotificationTemplateDefinition {
  eventKey: string;
  name: string;
  description: string;
  domain: "AUTH" | "COMMERCE_ORDER" | "COURIER" | "MERCHANT" | "DELIVERY_XY" | "PAYMENTS" | "SUPPORT" | "SYSTEM";
  audience: "CUSTOMER" | "MERCHANT" | "COURIER" | "ADMIN";
  channels: ("PUSH" | "IN_APP")[];
  pushTitle: string;
  pushBody: string;
  defaultPushTitle: string;
  defaultPushBody: string;
  allowedVariables: string[];
  action?: string;
  destinationRoute?: string;
  category: "Pedidos" | "Operaciones" | "Finanzas" | "Administración" | "Sistema" | "Transferencias" | "Seguridad";
  priority: "NORMAL" | "HIGH" | "URGENT";
  enabled: boolean;
  isCritical: boolean;
  version: number;
  updatedAt?: admin.firestore.Timestamp | null;
  updatedBy?: string | null;
  updatedByEmail?: string | null;
  createdAt?: admin.firestore.Timestamp | null;
}

/**
 * Catálogo Canónico en Memoria con los Defaults Inmutables de Fábrica.
 * Garantiza Fail-Safe absoluto: Si Firestore está caído o un template es corrupto,
 * la operación continúa sin interrupción.
 */
export const CANONICAL_TEMPLATE_DEFAULTS: Record<string, NotificationTemplateDefinition> = {
  WELCOME_CUSTOMER: {
    eventKey: "WELCOME_CUSTOMER",
    name: "Bienvenida al Cliente",
    description: "Enviado cuando un cliente nuevo completa por primera vez su registro en TuaniGo.",
    domain: "AUTH",
    audience: "CUSTOMER",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "👋 ¡Bienvenido a TuaniGo!",
    pushBody: "Tu nueva forma de pedir, enviar y moverte está aquí. Descubrí comercios, solicitá entregas y disfrutá TuaniGo.",
    defaultPushTitle: "👋 ¡Bienvenido a TuaniGo!",
    defaultPushBody: "Tu nueva forma de pedir, enviar y moverte está aquí. Descubrí comercios, solicitá entregas y disfrutá TuaniGo.",
    allowedVariables: ["customerName"],
    action: "WELCOME_FIRST_REGISTRATION",
    destinationRoute: "customer_dashboard",
    category: "Sistema",
    priority: "NORMAL",
    enabled: true,
    isCritical: false,
    version: 1,
  },
  ORDER_CREATED_MERCHANT: {
    eventKey: "ORDER_CREATED_MERCHANT",
    name: "Nuevo Pedido para Comercio",
    description: "Notifica al comercio cuando un cliente realiza un nuevo pedido en Commerce Delivery.",
    domain: "COMMERCE_ORDER",
    audience: "MERCHANT",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "🛒 ¡Nuevo Pedido Entrante!",
    pushBody: "[{{fulfillmentType}}] Pedido {{orderCode}} - Cliente: {{customerName}} - Total: C$ {{total}}",
    defaultPushTitle: "🛒 ¡Nuevo Pedido Entrante!",
    defaultPushBody: "[{{fulfillmentType}}] Pedido {{orderCode}} - Cliente: {{customerName}} - Total: C$ {{total}}",
    allowedVariables: ["fulfillmentType", "orderCode", "customerName", "total"],
    action: "NEW_ORDER",
    destinationRoute: "orders",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  COURIER_DIRECT_ASSIGNED: {
    eventKey: "COURIER_DIRECT_ASSIGNED",
    name: "Pedido Asignado al Motorizado",
    description: "Notifica al motorizado cuando es asignado directamente por el comercio o administración.",
    domain: "COURIER",
    audience: "COURIER",
    channels: ["PUSH"],
    pushTitle: "🛵 Nuevo pedido asignado",
    pushBody: "[{{businessName}}] Pedido #{{orderCode}} — Total: C$ {{total}}",
    defaultPushTitle: "🛵 Nuevo pedido asignado",
    defaultPushBody: "[{{businessName}}] Pedido #{{orderCode}} — Total: C$ {{total}}",
    allowedVariables: ["businessName", "orderCode", "total"],
    action: "COURIER_ASSIGNED",
    destinationRoute: "assigned_orders",
    category: "Operaciones",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  ORDER_READY_FLEET_POOL: {
    eventKey: "ORDER_READY_FLEET_POOL",
    name: "Pedido Listo para Pool de Motorizados",
    description: "Difunde a los motorizados del municipio que un pedido está listo para recoger.",
    domain: "COURIER",
    audience: "COURIER",
    channels: ["PUSH"],
    pushTitle: "🛵 Pedido Listo para Recoger",
    pushBody: "Comercio: {{businessName}} - Dir: {{destinationAddress}}",
    defaultPushTitle: "🛵 Pedido Listo para Recoger",
    defaultPushBody: "Comercio: {{businessName}} - Dir: {{destinationAddress}}",
    allowedVariables: ["businessName", "destinationAddress", "orderCode"],
    action: "NEW_ORDER",
    destinationRoute: "available_orders",
    category: "Operaciones",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  COMMERCE_ORDER_OFFER: {
    eventKey: "COMMERCE_ORDER_OFFER",
    name: "Oferta de Pedido Comercial Progresivo",
    description: "Notifica a los motorizados en el radio activo durante el despacho progresivo.",
    domain: "COURIER",
    audience: "COURIER",
    channels: ["PUSH"],
    pushTitle: "🛵 ¡Nueva entrega comercial disponible!",
    pushBody: "[{{businessName}}] Pedido #{{orderCode}} | Ganancia: C$ {{courierEarnings}} ({{distanceKm}} km)",
    defaultPushTitle: "🛵 ¡Nueva entrega comercial disponible!",
    defaultPushBody: "[{{businessName}}] Pedido #{{orderCode}} | Ganancia: C$ {{courierEarnings}} ({{distanceKm}} km)",
    allowedVariables: ["businessName", "orderCode", "courierEarnings", "distanceKm"],
    action: "COMMERCE_ORDER_OFFER",
    destinationRoute: "available_orders",
    category: "Operaciones",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  ORDER_RECEIVED_CUSTOMER: {
    eventKey: "ORDER_RECEIVED_CUSTOMER",
    name: "Pedido Recibido (Cliente)",
    description: "Notifica al cliente que su pedido fue recibido y está en proceso.",
    domain: "COMMERCE_ORDER",
    audience: "CUSTOMER",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "Pedido recibido",
    pushBody: "Estamos procesando tu pedido.",
    defaultPushTitle: "Pedido recibido",
    defaultPushBody: "Estamos procesando tu pedido.",
    allowedVariables: ["customerName", "orderCode", "businessName"],
    action: "OPEN_ORDER",
    destinationRoute: "order_detail",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: false,
    version: 1,
  },
  ORDER_PREPARING_RESTAURANT: {
    eventKey: "ORDER_PREPARING_RESTAURANT",
    name: "Pedido en Cocina (Restaurante)",
    description: "Notifica al cliente que un restaurante gastronómico está preparando su comida.",
    domain: "COMMERCE_ORDER",
    audience: "CUSTOMER",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "🍳 Pedido en Cocina",
    pushBody: "{{businessName}} está preparando tu pedido.",
    defaultPushTitle: "🍳 Pedido en Cocina",
    defaultPushBody: "{{businessName}} está preparando tu pedido.",
    allowedVariables: ["businessName", "orderCode", "customerName"],
    action: "OPEN_ORDER",
    destinationRoute: "order_detail",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: false,
    version: 1,
  },
  ORDER_PREPARING_RETAIL: {
    eventKey: "ORDER_PREPARING_RETAIL",
    name: "Pedido en Preparación (Tienda/Comercio)",
    description: "Notifica al cliente que un comercio o tienda está preparando su pedido.",
    domain: "COMMERCE_ORDER",
    audience: "CUSTOMER",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "📦 Tu pedido en Preparación",
    pushBody: "{{businessName}} está preparando tu pedido.",
    defaultPushTitle: "📦 Tu pedido en Preparación",
    defaultPushBody: "{{businessName}} está preparando tu pedido.",
    allowedVariables: ["businessName", "orderCode", "customerName"],
    action: "OPEN_ORDER",
    destinationRoute: "order_detail",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: false,
    version: 1,
  },
  ORDER_READY_CUSTOMER: {
    eventKey: "ORDER_READY_CUSTOMER",
    name: "Pedido Listo (Cliente)",
    description: "Notifica al cliente que su pedido está listo y pronto será entregado.",
    domain: "COMMERCE_ORDER",
    audience: "CUSTOMER",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "📦 Tu pedido está listo",
    pushBody: "Tu pedido está listo y pronto será entregado.",
    defaultPushTitle: "📦 Tu pedido está listo",
    defaultPushBody: "Tu pedido está listo y pronto será entregado.",
    allowedVariables: ["businessName", "orderCode", "customerName"],
    action: "OPEN_ORDER",
    destinationRoute: "order_detail",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: false,
    version: 1,
  },
  COURIER_ASSIGNED_CUSTOMER: {
    eventKey: "COURIER_ASSIGNED_CUSTOMER",
    name: "Repartidor Asignado (Cliente)",
    description: "Notifica al cliente que un motorizado ha sido asignado para entregar su pedido.",
    domain: "COMMERCE_ORDER",
    audience: "CUSTOMER",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "🛵 Repartidor asignado",
    pushBody: "Un motorizado ha sido asignado para entregar tu pedido.",
    defaultPushTitle: "🛵 Repartidor asignado",
    defaultPushBody: "Un motorizado ha sido asignado para entregar tu pedido.",
    allowedVariables: ["courierName", "businessName", "orderCode", "customerName"],
    action: "OPEN_ORDER",
    destinationRoute: "order_detail",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  COURIER_ACCEPTED_CUSTOMER: {
    eventKey: "COURIER_ACCEPTED_CUSTOMER",
    name: "Repartidor Confirmado (Cliente)",
    description: "Notifica al cliente que el repartidor aceptó y se dirige al comercio.",
    domain: "COMMERCE_ORDER",
    audience: "CUSTOMER",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "🛵 Repartidor confirmado",
    pushBody: "Tu repartidor aceptó el pedido y se dirige al comercio.",
    defaultPushTitle: "🛵 Repartidor confirmado",
    defaultPushBody: "Tu repartidor aceptó el pedido y se dirige al comercio.",
    allowedVariables: ["courierName", "businessName", "orderCode", "customerName"],
    action: "OPEN_ORDER",
    destinationRoute: "order_detail",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  ORDER_PICKED_UP_CUSTOMER: {
    eventKey: "ORDER_PICKED_UP_CUSTOMER",
    name: "Pedido Recogido por Motorizado (Cliente)",
    description: "Notifica al cliente que el motorizado recogió su pedido del comercio.",
    domain: "COMMERCE_ORDER",
    audience: "CUSTOMER",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "📦 Pedido recogido",
    pushBody: "El motorizado ha recogido tu pedido en el comercio.",
    defaultPushTitle: "📦 Pedido recogido",
    defaultPushBody: "El motorizado ha recogido tu pedido en el comercio.",
    allowedVariables: ["courierName", "businessName", "orderCode", "customerName"],
    action: "OPEN_TRACKING",
    destinationRoute: "order_tracking",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  ORDER_IN_TRANSIT_CUSTOMER: {
    eventKey: "ORDER_IN_TRANSIT_CUSTOMER",
    name: "Pedido en Camino (Cliente)",
    description: "Notifica al cliente que su pedido va en camino hacia su dirección.",
    domain: "COMMERCE_ORDER",
    audience: "CUSTOMER",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "🛵 Tu pedido está en camino",
    pushBody: "Tu repartidor lleva tu pedido en ruta hacia tu dirección.",
    defaultPushTitle: "🛵 Tu pedido está en camino",
    defaultPushBody: "Tu repartidor lleva tu pedido en ruta hacia tu dirección.",
    allowedVariables: ["courierName", "businessName", "orderCode", "customerName"],
    action: "OPEN_TRACKING",
    destinationRoute: "order_tracking",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  ORDER_DELIVERED_CUSTOMER: {
    eventKey: "ORDER_DELIVERED_CUSTOMER",
    name: "Pedido Entregado (Cliente)",
    description: "Notifica al cliente que su pedido fue entregado correctamente.",
    domain: "COMMERCE_ORDER",
    audience: "CUSTOMER",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "🎉 ¡Pedido entregado!",
    pushBody: "Tu pedido fue entregado correctamente.",
    defaultPushTitle: "🎉 ¡Pedido entregado!",
    defaultPushBody: "Tu pedido fue entregado correctamente.",
    allowedVariables: ["customerName", "orderCode", "businessName"],
    action: "OPEN_ORDER",
    destinationRoute: "order_detail",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  ORDER_COMPLETED_CUSTOMER: {
    eventKey: "ORDER_COMPLETED_CUSTOMER",
    name: "Pedido Completado (Cliente)",
    description: "Notifica al cliente que su pedido ha sido completado con éxito.",
    domain: "COMMERCE_ORDER",
    audience: "CUSTOMER",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "✓ Pedido completado",
    pushBody: "Tu pedido ha sido completado con éxito.",
    defaultPushTitle: "✓ Pedido completado",
    defaultPushBody: "Tu pedido ha sido completado con éxito.",
    allowedVariables: ["customerName", "orderCode", "businessName"],
    action: "OPEN_ORDER",
    destinationRoute: "order_detail",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: false,
    version: 1,
  },
  ORDER_CANCELLED_CUSTOMER: {
    eventKey: "ORDER_CANCELLED_CUSTOMER",
    name: "Pedido Cancelado (Cliente)",
    description: "Notifica al cliente cuando su pedido es cancelado con motivo.",
    domain: "COMMERCE_ORDER",
    audience: "CUSTOMER",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "🚫 Pedido cancelado",
    pushBody: "{{cancelReason}}",
    defaultPushTitle: "🚫 Pedido cancelado",
    defaultPushBody: "{{cancelReason}}",
    allowedVariables: ["cancelReason", "orderCode", "businessName", "customerName"],
    action: "OPEN_ORDER",
    destinationRoute: "order_detail",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  COURIER_ASSIGNED_MERCHANT: {
    eventKey: "COURIER_ASSIGNED_MERCHANT",
    name: "Motorizado Asignado (Comercio)",
    description: "Notifica al comercio que un motorizado fue asignado para recoger el pedido.",
    domain: "COMMERCE_ORDER",
    audience: "MERCHANT",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "🛵 Motorizado Asignado (#{{orderCode}})",
    pushBody: "{{courierName}} ha sido asignado para recoger el pedido de {{customerName}}.",
    defaultPushTitle: "🛵 Motorizado Asignado (#{{orderCode}})",
    defaultPushBody: "{{courierName}} ha sido asignado para recoger el pedido de {{customerName}}.",
    allowedVariables: ["orderCode", "courierName", "customerName"],
    action: "OPEN_ORDER",
    destinationRoute: "orders",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  ORDER_READY_MERCHANT: {
    eventKey: "ORDER_READY_MERCHANT",
    name: "Pedido Marcado como Listo (Comercio)",
    description: "Confirma al comercio que el pedido está listo para recolección.",
    domain: "COMMERCE_ORDER",
    audience: "MERCHANT",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "📦 Pedido Listo para Despacho (#{{orderCode}})",
    pushBody: "Pedido marcado como listo. Esperando recolección por motorizado.",
    defaultPushTitle: "📦 Pedido Listo para Despacho (#{{orderCode}})",
    defaultPushBody: "Pedido marcado como listo. Esperando recolección por motorizado.",
    allowedVariables: ["orderCode"],
    action: "OPEN_ORDER",
    destinationRoute: "orders",
    category: "Pedidos",
    priority: "NORMAL",
    enabled: true,
    isCritical: false,
    version: 1,
  },
  ORDER_PICKED_UP_MERCHANT: {
    eventKey: "ORDER_PICKED_UP_MERCHANT",
    name: "Pedido Recogido (Comercio)",
    description: "Notifica al comercio que el motorizado ha recogido el paquete.",
    domain: "COMMERCE_ORDER",
    audience: "MERCHANT",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "📦 Pedido Recogido (#{{orderCode}})",
    pushBody: "{{courierName}} ha recogido el pedido y se dirige al cliente.",
    defaultPushTitle: "📦 Pedido Recogido (#{{orderCode}})",
    defaultPushBody: "{{courierName}} ha recogido el pedido y se dirige al cliente.",
    allowedVariables: ["orderCode", "courierName", "customerName"],
    action: "OPEN_ORDER",
    destinationRoute: "orders",
    category: "Pedidos",
    priority: "NORMAL",
    enabled: true,
    isCritical: false,
    version: 1,
  },
  ORDER_IN_TRANSIT_MERCHANT: {
    eventKey: "ORDER_IN_TRANSIT_MERCHANT",
    name: "Pedido en Ruta (Comercio)",
    description: "Informa al comercio que el pedido va en ruta hacia el cliente.",
    domain: "COMMERCE_ORDER",
    audience: "MERCHANT",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "🛵 Pedido en Camino (#{{orderCode}})",
    pushBody: "El pedido va en ruta hacia la dirección del cliente ({{customerName}}).",
    defaultPushTitle: "🛵 Pedido en Camino (#{{orderCode}})",
    defaultPushBody: "El pedido va en ruta hacia la dirección del cliente ({{customerName}}).",
    allowedVariables: ["orderCode", "customerName"],
    action: "OPEN_ORDER",
    destinationRoute: "orders",
    category: "Pedidos",
    priority: "NORMAL",
    enabled: true,
    isCritical: false,
    version: 1,
  },
  ORDER_DELIVERED_MERCHANT: {
    eventKey: "ORDER_DELIVERED_MERCHANT",
    name: "Pedido Entregado (Comercio)",
    description: "Notifica al comercio que el pedido fue entregado con éxito al cliente.",
    domain: "COMMERCE_ORDER",
    audience: "MERCHANT",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "✅ ¡Pedido Entregado! (#{{orderCode}})",
    pushBody: "El pedido fue entregado con éxito a {{customerName}}. Total: C$ {{total}}",
    defaultPushTitle: "✅ ¡Pedido Entregado! (#{{orderCode}})",
    defaultPushBody: "El pedido fue entregado con éxito a {{customerName}}. Total: C$ {{total}}",
    allowedVariables: ["orderCode", "customerName", "total"],
    action: "OPEN_ORDER",
    destinationRoute: "orders",
    category: "Pedidos",
    priority: "NORMAL",
    enabled: true,
    isCritical: false,
    version: 1,
  },
  ORDER_CANCELLED_MERCHANT: {
    eventKey: "ORDER_CANCELLED_MERCHANT",
    name: "Pedido Cancelado (Comercio)",
    description: "Notifica al comercio que el pedido fue cancelado.",
    domain: "COMMERCE_ORDER",
    audience: "MERCHANT",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "🚫 Pedido Cancelado (#{{orderCode}})",
    pushBody: "Motivo: {{cancelReason}}",
    defaultPushTitle: "🚫 Pedido Cancelado (#{{orderCode}})",
    defaultPushBody: "Motivo: {{cancelReason}}",
    allowedVariables: ["orderCode", "cancelReason", "customerName"],
    action: "OPEN_ORDER",
    destinationRoute: "orders",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  PAYMENT_PROOF_REJECTED_CUSTOMER: {
    eventKey: "PAYMENT_PROOF_REJECTED_CUSTOMER",
    name: "Comprobante de Pago Rechazado",
    description: "Notifica al cliente cuando su comprobante de transferencia bancaria fue rechazado.",
    domain: "PAYMENTS",
    audience: "CUSTOMER",
    channels: ["PUSH"],
    pushTitle: "❌ Comprobante no verificado",
    pushBody: "Motivo: {{rejectionReason}}. Revisa tu pago.",
    defaultPushTitle: "❌ Comprobante no verificado",
    defaultPushBody: "Motivo: {{rejectionReason}}. Revisa tu pago.",
    allowedVariables: ["rejectionReason", "orderCode"],
    action: "PAYMENT_REJECTED",
    destinationRoute: "order_detail",
    category: "Finanzas",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  PAYMENT_MAX_ATTEMPTS_CANCELLED: {
    eventKey: "PAYMENT_MAX_ATTEMPTS_CANCELLED",
    name: "Pedido Cancelado por Límite de Comprobantes",
    description: "Notifica la cancelación automática tras superar los intentos de comprobante.",
    domain: "PAYMENTS",
    audience: "CUSTOMER",
    channels: ["PUSH"],
    pushTitle: "🚫 Pedido Cancelado",
    pushBody: "Tu pedido fue cancelado al superar el límite de intentos de comprobantes.",
    defaultPushTitle: "🚫 Pedido Cancelado",
    defaultPushBody: "Tu pedido fue cancelado al superar el límite de intentos de comprobantes.",
    allowedVariables: ["orderCode"],
    action: "ORDER_CANCELLED",
    destinationRoute: "order_detail",
    category: "Finanzas",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  NEW_X_TO_Y_DELIVERY: {
    eventKey: "NEW_X_TO_Y_DELIVERY",
    name: "Nueva Encomienda Express X→Y al Pool",
    description: "Difusión de nueva encomienda al pool de motorizados.",
    domain: "DELIVERY_XY",
    audience: "COURIER",
    channels: ["PUSH"],
    pushTitle: "📦 ¡Nueva Encomienda X→Y!",
    pushBody: "{{packageDescription}} | {{originAddress}} → {{destinationAddress}} | {{payer}} C${{customerOffer}}",
    defaultPushTitle: "📦 ¡Nueva Encomienda X→Y!",
    defaultPushBody: "{{packageDescription}} | {{originAddress}} → {{destinationAddress}} | {{payer}} C${{customerOffer}}",
    allowedVariables: ["packageDescription", "originAddress", "destinationAddress", "payer", "customerOffer"],
    action: "NEW_X_TO_Y_DELIVERY",
    destinationRoute: "courier_dashboard",
    category: "Operaciones",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  XY_TARGETED_OFFER_COURIER: {
    eventKey: "XY_TARGETED_OFFER_COURIER",
    name: "Oferta Dirigida Encomienda X→Y (Radio)",
    description: "Notificación dirigida por radio de búsqueda para encomienda X→Y.",
    domain: "DELIVERY_XY",
    audience: "COURIER",
    channels: ["PUSH"],
    pushTitle: "📦 ¡Nueva Encomienda X→Y ({{radiusKm}} km)!",
    pushBody: "{{originAddress}} → {{destinationAddress}} | Oferta: C${{customerOffer}}",
    defaultPushTitle: "📦 ¡Nueva Encomienda X→Y ({{radiusKm}} km)!",
    defaultPushBody: "{{originAddress}} → {{destinationAddress}} | Oferta: C${{customerOffer}}",
    allowedVariables: ["radiusKm", "originAddress", "destinationAddress", "customerOffer"],
    action: "NEW_X_TO_Y_DELIVERY",
    destinationRoute: "courier_dashboard",
    category: "Operaciones",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  XY_TRIP_CANCELLED_COURIER: {
    eventKey: "XY_TRIP_CANCELLED_COURIER",
    name: "Encomienda Cancelada (Motorizado)",
    description: "Notifica al motorizado asignado que la encomienda fue cancelada.",
    domain: "DELIVERY_XY",
    audience: "COURIER",
    channels: ["PUSH"],
    pushTitle: "❌ Encomienda cancelada",
    pushBody: "La encomienda #{{tripShortCode}} ya no requiere recogida.",
    defaultPushTitle: "❌ Encomienda cancelada",
    defaultPushBody: "La encomienda #{{tripShortCode}} ya no requiere recogida.",
    allowedVariables: ["tripShortCode"],
    action: "TRIP_CANCELLED",
    destinationRoute: "courier_dashboard",
    category: "Operaciones",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  XY_TRIP_CANCELLED_CUSTOMER: {
    eventKey: "XY_TRIP_CANCELLED_CUSTOMER",
    name: "Encomienda Cancelada (Cliente)",
    description: "Notifica al cliente que su encomienda fue cancelada por administración.",
    domain: "DELIVERY_XY",
    audience: "CUSTOMER",
    channels: ["PUSH"],
    pushTitle: "❌ Encomienda cancelada",
    pushBody: "Tu encomienda #{{tripShortCode}} fue cancelada por administración.",
    defaultPushTitle: "❌ Encomienda cancelada",
    defaultPushBody: "Tu encomienda #{{tripShortCode}} fue cancelada por administración.",
    allowedVariables: ["tripShortCode"],
    action: "TRIP_CANCELLED",
    destinationRoute: "customer_dashboard",
    category: "Operaciones",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  XY_TRANSFER_VERIFY_ADMIN: {
    eventKey: "XY_TRANSFER_VERIFY_ADMIN",
    name: "Comprobante X→Y Pendiente (Admin)",
    description: "Alerta operativa para administración ante comprobante bancario express pendiente.",
    domain: "DELIVERY_XY",
    audience: "ADMIN",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "💳 Transferencia pendiente de verificación",
    pushBody: "La encomienda X→Y #{{tripShortCode}} tiene un comprobante pendiente de revisión por C$ {{amount}}.",
    defaultPushTitle: "💳 Transferencia pendiente de verificación",
    defaultPushBody: "La encomienda X→Y #{{tripShortCode}} tiene un comprobante pendiente de revisión por C$ {{amount}}.",
    allowedVariables: ["tripShortCode", "amount"],
    action: "OPEN_X_TO_Y_TRANSFER_VERIFICATION",
    destinationRoute: "delivery_express_transfer_verification",
    category: "Transferencias",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  // ─── FASE 5: RECORDATORIOS Y ORQUESTACIÓN PROGRAMADA (BSD-SCHEDULED-COMMERCE-PHASE-5-REMINDERS-001) ───
  SCHEDULED_MERCHANT_24H: {
    eventKey: "SCHEDULED_MERCHANT_24H",
    name: "Recordatorio Pedido Programado 24h (Comercio)",
    description: "Notifica al comercio aproximadamente 24 horas antes de la entrega programada de un pedido.",
    domain: "COMMERCE_ORDER",
    audience: "MERCHANT",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "📅 Pedido programado para mañana",
    pushBody: "El pedido #{{orderCode}} debe entregarse mañana entre {{deliveryWindow}}.",
    defaultPushTitle: "📅 Pedido programado para mañana",
    defaultPushBody: "El pedido #{{orderCode}} debe entregarse mañana entre {{deliveryWindow}}.",
    allowedVariables: ["orderCode", "deliveryWindow", "customerName", "orderId"],
    action: "OPEN_ORDER",
    destinationRoute: "orders",
    category: "Pedidos",
    priority: "NORMAL",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  SCHEDULED_CUSTOMER_24H: {
    eventKey: "SCHEDULED_CUSTOMER_24H",
    name: "Recordatorio Pedido Programado 24h (Cliente)",
    description: "Confirma al comprador aproximadamente 24 horas antes que su pedido está programado para el día siguiente.",
    domain: "COMMERCE_ORDER",
    audience: "CUSTOMER",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "📅 Tu pedido está programado para mañana",
    pushBody: "Tu pedido de {{businessName}} (#{{orderCode}}) está programado para entrega mañana entre {{deliveryWindow}}.",
    defaultPushTitle: "📅 Tu pedido está programado para mañana",
    defaultPushBody: "Tu pedido de {{businessName}} (#{{orderCode}}) está programado para entrega mañana entre {{deliveryWindow}}.",
    allowedVariables: ["orderCode", "deliveryWindow", "businessName", "orderId"],
    action: "OPEN_ORDER",
    destinationRoute: "order_detail",
    category: "Pedidos",
    priority: "NORMAL",
    enabled: true,
    isCritical: false,
    version: 1,
  },
  SCHEDULED_MERCHANT_5H: {
    eventKey: "SCHEDULED_MERCHANT_5H",
    name: "Recordatorio Operativo Pedido Programado 5h (Comercio)",
    description: "Alerta de alta prioridad al comercio aproximadamente 5 horas antes de la entrega del pedido.",
    domain: "COMMERCE_ORDER",
    audience: "MERCHANT",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "⏰ Pedido programado próximo",
    pushBody: "Faltan 5 horas para la entrega del pedido #{{orderCode}}.",
    defaultPushTitle: "⏰ Pedido programado próximo",
    defaultPushBody: "Faltan 5 horas para la entrega del pedido #{{orderCode}}.",
    allowedVariables: ["orderCode", "deliveryWindow", "customerName", "orderId"],
    action: "OPEN_ORDER",
    destinationRoute: "orders",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  SCHEDULED_CUSTOMER_5H: {
    eventKey: "SCHEDULED_CUSTOMER_5H",
    name: "Recordatorio de Entrega Hoy 5h (Cliente)",
    description: "Informa al cliente el mismo día de la entrega que su pedido programado llegará hoy.",
    domain: "COMMERCE_ORDER",
    audience: "CUSTOMER",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "⏰ Tu pedido está programado para hoy",
    pushBody: "Tu pedido de {{businessName}} (#{{orderCode}}) está programado para entrega hoy entre {{deliveryWindow}}.",
    defaultPushTitle: "⏰ Tu pedido está programado para hoy",
    defaultPushBody: "Tu pedido de {{businessName}} (#{{orderCode}}) está programado para entrega hoy entre {{deliveryWindow}}.",
    allowedVariables: ["orderCode", "deliveryWindow", "businessName", "orderId"],
    action: "OPEN_ORDER",
    destinationRoute: "order_detail",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: false,
    version: 1,
  },
  SCHEDULED_MERCHANT_PREPARATION_DUE: {
    eventKey: "SCHEDULED_MERCHANT_PREPARATION_DUE",
    name: "Alerta Ventana de Preparación (Comercio)",
    description: "Notifica al comercio cuando el pedido entra en su ventana de preparación según preparationLeadMinutes.",
    domain: "COMMERCE_ORDER",
    audience: "MERCHANT",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "🧑‍🍳 Es momento de preparar este pedido",
    pushBody: "El pedido #{{orderCode}} está entrando en su ventana de preparación.",
    defaultPushTitle: "🧑‍🍳 Es momento de preparar este pedido",
    defaultPushBody: "El pedido #{{orderCode}} está entrando en su ventana de preparación.",
    allowedVariables: ["orderCode", "deliveryWindow", "preparationLeadMinutes", "orderId"],
    action: "OPEN_ORDER",
    destinationRoute: "orders",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
  SCHEDULED_MERCHANT_WINDOW_RISK: {
    eventKey: "SCHEDULED_MERCHANT_WINDOW_RISK",
    name: "Alerta Pedido Programado en Riesgo (Comercio)",
    description: "Alerta urgente al comercio si la ventana de entrega está próxima o inició y el pedido aún no está listo.",
    domain: "COMMERCE_ORDER",
    audience: "MERCHANT",
    channels: ["PUSH", "IN_APP"],
    pushTitle: "⚠️ Pedido programado en riesgo",
    pushBody: "El pedido #{{orderCode}} aún no está listo y su ventana de entrega está próxima.",
    defaultPushTitle: "⚠️ Pedido programado en riesgo",
    defaultPushBody: "El pedido #{{orderCode}} aún no está listo y su ventana de entrega está próxima.",
    allowedVariables: ["orderCode", "deliveryWindow", "orderId"],
    action: "OPEN_ORDER",
    destinationRoute: "orders",
    category: "Pedidos",
    priority: "HIGH",
    enabled: true,
    isCritical: true,
    version: 1,
  },
};

/**
 * Servicio Singleton de Plantillas de Notificaciones Transaccionales
 */
export class NotificationTemplateService {
  private static cache: Map<string, { template: NotificationTemplateDefinition; cachedAt: number }> = new Map();
  private static CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutos de caché en memoria

  /**
   * Obtiene la definición de una plantilla desde Firestore o memoria.
   */
  public static async getTemplate(eventKey: string): Promise<NotificationTemplateDefinition> {
    const canonicalDefault = CANONICAL_TEMPLATE_DEFAULTS[eventKey];
    if (!canonicalDefault) {
      Logger.warn(`[NOTIFICATION_TEMPLATE] EventKey '${eventKey}' no registrado en CANONICAL_TEMPLATE_DEFAULTS.`);
    }

    const now = Date.now();
    const cached = this.cache.get(eventKey);
    if (cached && now - cached.cachedAt < this.CACHE_TTL_MS) {
      return cached.template;
    }

    try {
      const db = admin.firestore();
      const docSnap = await db.collection("notification_templates").doc(eventKey).get();

      if (docSnap.exists) {
        const firestoreData = docSnap.data() as Partial<NotificationTemplateDefinition>;
        const mergedTemplate: NotificationTemplateDefinition = {
          ...(canonicalDefault || ({} as any)),
          ...firestoreData,
          eventKey,
          pushTitle: firestoreData.pushTitle?.trim() || canonicalDefault?.pushTitle || "Notificación de Sistema",
          pushBody: firestoreData.pushBody?.trim() || canonicalDefault?.pushBody || "Tienes una nueva actualización.",
          defaultPushTitle: canonicalDefault?.defaultPushTitle || firestoreData.defaultPushTitle || "",
          defaultPushBody: canonicalDefault?.defaultPushBody || firestoreData.defaultPushBody || "",
          allowedVariables: canonicalDefault?.allowedVariables || firestoreData.allowedVariables || [],
          action: canonicalDefault?.action || firestoreData.action || "NOTIFICATION",
          destinationRoute: canonicalDefault?.destinationRoute || firestoreData.destinationRoute || "",
          category: firestoreData.category || canonicalDefault?.category || "Sistema",
          priority: firestoreData.priority || canonicalDefault?.priority || "NORMAL",
          enabled: firestoreData.enabled !== false,
          isCritical: canonicalDefault?.isCritical ?? false,
          version: typeof firestoreData.version === "number" ? firestoreData.version : 1,
        };

        this.cache.set(eventKey, { template: mergedTemplate, cachedAt: now });
        return mergedTemplate;
      }
    } catch (err: any) {
      Logger.warn(`[NOTIFICATION_TEMPLATE] Error leyendo Firestore para template '${eventKey}', usando default canónico:`, err?.message);
    }

    if (canonicalDefault) {
      this.cache.set(eventKey, { template: canonicalDefault, cachedAt: now });
      return canonicalDefault;
    }

    // Fallback absoluto de emergencia
    return {
      eventKey,
      name: eventKey,
      description: "Plantilla genérica de fallback",
      domain: "SYSTEM",
      audience: "CUSTOMER",
      channels: ["PUSH", "IN_APP"],
      pushTitle: "TuaniGo",
      pushBody: "Tienes una nueva actualización de tu servicio.",
      defaultPushTitle: "TuaniGo",
      defaultPushBody: "Tienes una nueva actualización de tu servicio.",
      allowedVariables: [],
      category: "Sistema",
      priority: "NORMAL",
      enabled: true,
      isCritical: false,
      version: 1,
    };
  }

  /**
   * Resuelve el título y cuerpo de una notificación interpolando variables de forma segura.
   */
  public static async resolve(
    eventKey: string,
    contextVariables: Record<string, any> = {}
  ): Promise<{
    title: string;
    body: string;
    action: string;
    destinationRoute: string;
    category: "Pedidos" | "Operaciones" | "Finanzas" | "Administración" | "Sistema" | "Transferencias" | "Seguridad";
    priority: "NORMAL" | "HIGH" | "URGENT";
    enabled: boolean;
  }> {
    const template = await this.getTemplate(eventKey);

    const title = this.interpolate(template.pushTitle, template.allowedVariables, contextVariables);
    const body = this.interpolate(template.pushBody, template.allowedVariables, contextVariables);

    return {
      title,
      body,
      action: template.action || "NOTIFICATION",
      destinationRoute: template.destinationRoute || "",
      category: template.category,
      priority: template.priority,
      enabled: template.enabled,
    };
  }

  /**
   * Limpia la caché en memoria para una plantilla específica o todas.
   */
  public static invalidateCache(eventKey?: string): void {
    if (eventKey) {
      this.cache.delete(eventKey);
    } else {
      this.cache.clear();
    }
  }

  /**
   * Interpolador seguro de variables. Solo reemplaza claves en allowedVariables.
   */
  private static interpolate(text: string, allowedVariables: string[], context: Record<string, any>): string {
    if (!text || typeof text !== "string") return "";

    return text.replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g, (match, varName) => {
      if (!allowedVariables.includes(varName)) {
        return ""; // Variable no autorizada
      }
      const val = context[varName];
      if (val !== undefined && val !== null) {
        return String(val);
      }
      return "";
    });
  }
}
